import { loadAllData } from "./lib/load-data";
import { candidateStatusSchema } from "../src/lib/schemas";
import { territoryReviewReportSchema } from "../src/lib/territories";
import fs from "node:fs";
import path from "node:path";
import { verifiedGeometryRegistrySchema } from "../src/lib/geometry";

const { election, shards } = loadAllData();
const candidates = shards.flatMap((shard) => shard.candidates);
const districts = shards.flatMap((shard) => shard.districts.map((district) => ({ ...district, candidates: shard.candidates.filter((candidate) => candidate.district_number === district.number) })));
const resourceIds = new Set(shards.flatMap((shard) => shard.resources.map((item) => item.candidate_id)));
const newsIds = new Set(shards.flatMap((shard) => shard.news.map((item) => item.candidate_id)));
const biographyIds = new Set(candidates.filter((candidate) => candidate.biography.length > 0).map((candidate) => candidate.id));
const contactIds = new Set(candidates.filter((candidate) => candidate.contacts.length > 0).map((candidate) => candidate.id));
const candidatesWithDecision = candidates.filter((candidate) => candidate.status_history.some((event) => event.decision));
const decisionDistricts = new Set(candidatesWithDecision.map((candidate) => candidate.district_number));
const decisionRegions = shards.filter((shard) => shard.candidates.some((candidate) => candidate.status_history.some((event) => event.decision)));
const territoryCoverage = territoryReviewReportSchema.parse(JSON.parse(fs.readFileSync(path.join(process.cwd(), "data", "territories", "review-report.json"), "utf8")));
const geometryCoverage = verifiedGeometryRegistrySchema.parse(JSON.parse(fs.readFileSync(path.join(process.cwd(), "data", "geometry", "verified-districts.json"), "utf8")));

console.log(`Coverage report · ${election.data_as_of} · ${election.dataset_kind}`);
console.log(`Регионы: ${shards.length}`);
console.log(`Округа: ${districts.length}/${election.expected_district_count}`);
console.log(`Кандидаты: ${candidates.length}`);
console.log(`Партийные выдвижения: ${candidates.filter((candidate) => candidate.nomination_type === "party").length}`);
console.log(`Проверенные самовыдвижения: ${candidates.filter((candidate) => candidate.nomination_type === "self").length}`);
console.log(`Кандидаты с решением комиссии: ${candidatesWithDecision.length}`);
console.log(`Округа с решениями комиссии: ${decisionDistricts.size}/${districts.length}`);
console.log(`Регионы с решениями комиссии: ${decisionRegions.length}/${shards.length}`);
console.log(`Статусы кандидатов на: ${election.candidate_status_as_of ?? election.data_as_of}`);
console.log(`Статусы: ${candidateStatusSchema.options.map((status) => `${status}=${candidates.filter((candidate) => candidate.status === status).length}`).join(", ")}`);
console.log(`Территориальные описания: ${territoryCoverage.source_descriptions}/${districts.length}`);
console.log(`Структурированные подписи территорий: ${territoryCoverage.structured}/${districts.length}`);
console.log(`Требуют проверки по источнику границ: ${territoryCoverage.review_required}/${districts.length}`);
console.log(`Округа с проверенной геометрией: ${geometryCoverage.geometries.length}/${districts.length}`);
console.log(`Fallback по официальным территориальным подписям: ${territoryCoverage.structured}/${districts.length}`);
console.log(`Округа без кандидатов: ${districts.filter((district) => district.candidates.length === 0).length}`);
console.log(`Кандидаты без подтвержденных ресурсов: ${candidates.filter((candidate) => !resourceIds.has(candidate.id)).length}`);
console.log(`Кандидаты без проверенных публикаций: ${candidates.filter((candidate) => !newsIds.has(candidate.id)).length}`);
console.log(`Кандидаты с проверенной биографией: ${biographyIds.size}/${candidates.length}`);
console.log(`Кандидаты с публичными служебными контактами: ${contactIds.size}/${candidates.length}`);
console.log(`Кандидаты с подтвержденными ресурсами: ${resourceIds.size}/${candidates.length}`);
console.log(`Кандидаты с проверенными публикациями: ${newsIds.size}/${candidates.length}`);
console.log(`Статус уточняется: ${candidates.filter((candidate) => candidate.status === "status_pending_verification").length}`);
